#!/usr/bin/env node
/**
 * The privacy policy, turned into the page the worker serves.
 *
 *   node tools/privacy-page.mjs        # writes apps/proxy/src/privacy.generated.ts
 *
 * Generated rather than written twice. A policy that exists in two places is a
 * policy that will say two things, and the one a reader sees is the one nobody
 * edits. `docs/privacy.md` is the source; a test asserts the committed page
 * matches what this produces.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const SOURCE = path.join(root, 'docs/privacy.md')
const OUT = path.join(root, 'apps/proxy/src/privacy.generated.ts')

const escape = (value) =>
  value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/** Just enough Markdown for this document, and nothing that needs a parser. */
export function toHtml(markdown) {
  const out = []
  let inTable = false
  let inList = false

  const closeList = () => { if (inList) { out.push('</ul>'); inList = false } }
  const closeTable = () => { if (inTable) { out.push('</tbody></table>'); inTable = false } }

  const inline = (text) =>
    escape(text)
      .replace(/`([^`]+)`/g, '<code>$1</code>')
      .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
      .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (whole, label, href) =>
        href.endsWith('.md') || href.startsWith('..') ? label : `<a href="${href}">${label}</a>`)

  /**
   * Wrapped prose is one paragraph, not one per line.
   *
   * This ran line by line, so a source line was a `<p>` and a `**bold**`
   * opened on one line and closed on the next matched nothing — both markers
   * went to the served page as literal asterisks. Found by reading the
   * deployed page rather than the generator: the markup was valid, and the
   * sentence was broken.
   */
  const joined = []
  let paragraph = []
  const flush = () => {
    if (paragraph.length > 0) {
      joined.push(paragraph.join(' '))
      paragraph = []
    }
  }
  for (const raw of markdown.split('\n')) {
    const structural =
      raw.trim() === '' || raw.startsWith('|') || raw.startsWith('- ') || raw.startsWith('#')
    if (structural) {
      flush()
      joined.push(raw)
    } else {
      paragraph.push(raw.trim())
    }
  }
  flush()

  for (const line of joined) {
    if (/^\|\s*-+/.test(line)) continue
    if (line.startsWith('|')) {
      const cells = line.split('|').slice(1, -1).map((c) => inline(c.trim()))
      if (!inTable) {
        closeList()
        out.push('<table><thead><tr>' + cells.map((c) => `<th>${c}</th>`).join('') + '</tr></thead><tbody>')
        inTable = true
      } else {
        out.push('<tr>' + cells.map((c) => `<td>${c}</td>`).join('') + '</tr>')
      }
      continue
    }
    closeTable()

    if (line.startsWith('- ')) {
      if (!inList) { out.push('<ul>'); inList = true }
      out.push(`<li>${inline(line.slice(2))}</li>`)
      continue
    }
    closeList()

    if (line.startsWith('## ')) out.push(`<h2>${inline(line.slice(3))}</h2>`)
    else if (line.startsWith('# ')) out.push(`<h1>${inline(line.slice(2))}</h1>`)
    else if (line.trim() !== '') out.push(`<p>${inline(line)}</p>`)
  }
  closeList()
  closeTable()
  return out.join('\n')
}

if (import.meta.filename === process.argv[1]) {
  const html = toHtml(readFileSync(SOURCE, 'utf8'))
  writeFileSync(
    OUT,
    `// Generated by tools/privacy-page.mjs from docs/privacy.md. Do not edit by hand.\n` +
      `export const PRIVACY_HTML = ${JSON.stringify(html)}\n`,
  )
  console.log(`wrote ${path.relative(root, OUT)} (${html.length} bytes of markup)`)
}
