#!/usr/bin/env node
/**
 * The stylesheet the public pages inline.
 *
 *   node tools/public-style.mjs   # writes apps/proxy/src/style.generated.ts
 *
 * Three screens are served by the worker — the landing page, the privacy page and the domain
 * status page — and on 2026-08-21 all three shipped with **no visual layer at all**: Times
 * New Roman, browser bullets, text edge to edge across a 1280px window. The markup was
 * right, the copy was right, the metadata was right (charset, viewport, title, description,
 * canonical, JSON-LD), and the pages read like an abandoned document. Found by rendering
 * them and looking — the same axis that found the dashboard shipping without a single style
 * rule (B-99), on the surfaces a stranger meets first.
 *
 * Why generated rather than written: the tokens are `packages/ui/src/tokens.ts`, and a worker
 * has no filesystem at runtime and no CSS build of its own. A hand-copied palette here would
 * be the second place a colour lives, which this project refuses everywhere else.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { toCss } from './tokens.mjs'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const OUT = path.join(root, 'apps/proxy/src/style.generated.ts')

/**
 * The page rules, over the markup the router already emits — no class names, no wrappers.
 *
 * Two deliberate differences from the extension's own `pages.css`:
 *
 *   - **lists keep their markers.** In the app a list is a structure (a queue, a log) and the
 *     browser's bullets are noise. Here they are prose — "what it does", "what it does not" —
 *     and prose in a bulleted list is what bullets are for. That stylesheet's own comment
 *     said the opt-in would arrive with the change that needed it; this is that change.
 *   - **a measure.** The app's screens are panels inside a page; these are documents, and a
 *     line of eighty Cyrillic characters is not read, it is skimmed and abandoned.
 */
const PAGE = `
  html { color-scheme: light dark; }
  body {
    margin: 0;
    padding: var(--ok-space-5);
    background: var(--ok-colour-surface-sunken);
    color: var(--ok-colour-text);
    font-family: var(--ok-type-font-family);
    font-size: var(--ok-type-size-base);
    line-height: var(--ok-type-line-base);
  }
  main {
    max-inline-size: var(--ok-size-page-max);
    margin-inline: auto;
    padding: var(--ok-space-5);
    background: var(--ok-colour-surface);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border);
    border-radius: var(--ok-shape-radius-lg);
  }
  h1 {
    margin: 0 0 var(--ok-space-3);
    font-size: var(--ok-type-size-xl);
    line-height: var(--ok-type-line-tight);
    font-weight: var(--ok-type-weight-strong);
  }
  h2 {
    margin: var(--ok-space-5) 0 var(--ok-space-2);
    font-size: var(--ok-type-size-lg);
    line-height: var(--ok-type-line-tight);
    font-weight: var(--ok-type-weight-strong);
  }
  p { margin: 0 0 var(--ok-space-3); }
  ul, ol { margin: 0 0 var(--ok-space-3); padding-inline-start: var(--ok-space-5); }
  li { margin-block: var(--ok-space-1); }
  a { color: var(--ok-colour-focus); }
  code, pre {
    font-family: var(--ok-type-font-mono);
    font-size: var(--ok-type-size-sm);
  }
  pre {
    padding: var(--ok-space-3);
    background: var(--ok-colour-surface-sunken);
    border-radius: var(--ok-shape-radius);
    overflow-x: auto;
  }
  table { border-collapse: collapse; inline-size: 100%; }
  th, td {
    padding: var(--ok-space-2);
    border-block-end: var(--ok-shape-hairline) solid var(--ok-colour-border);
    text-align: start;
    vertical-align: top;
  }
  form { display: flex; flex-wrap: wrap; gap: var(--ok-space-2); align-items: center; }
  label { color: var(--ok-colour-text-muted); }
  input {
    min-block-size: var(--ok-shape-target-min);
    padding: var(--ok-space-1) var(--ok-space-2);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border-strong);
    border-radius: var(--ok-shape-radius);
    background: var(--ok-colour-surface);
    color: var(--ok-colour-text);
    font: inherit;
  }
  button {
    min-block-size: var(--ok-shape-target-min);
    padding: var(--ok-space-1) var(--ok-space-3);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border-strong);
    border-radius: var(--ok-shape-radius);
    background: var(--ok-colour-text);
    color: var(--ok-colour-surface);
    font: inherit;
    cursor: pointer;
  }
  :focus-visible { outline: 2px solid var(--ok-colour-focus); outline-offset: 2px; }
`

/** The whole sheet: the tokens the product already declares, then the page rules. */
export function toStyle() {
  return `${toCss()}${PAGE}`
}

export function toModule() {
  return (
    '/* Generated by tools/public-style.mjs from packages/ui/src/tokens.ts. Do not edit by hand. */\n' +
    '\n' +
    '/** Inlined by the worker: three public pages, one visual layer, tokens from one place. */\n' +
    'export const PUBLIC_STYLE = `' +
    toStyle().replace(/[\\`$]/g, (ch) => `\\${ch}`) +
    '`\n'
  )
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  writeFileSync(OUT, toModule())
  console.log(`wrote ${path.relative(root, OUT)}`)
}
