#!/usr/bin/env node
/**
 * Turns the token module into the CSS the pages actually read.
 *
 *   node tools/tokens.mjs      # writes apps/extension/src/tokens.generated.css
 *
 * Generated so a value exists once. Two files holding the same colour is two
 * colours the day one of them changes, and this repository already refuses that
 * for its wireframes, its icons and its privacy page.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const root = path.resolve(import.meta.dirname, '..')
const OUT = path.join(root, 'apps/extension/src/tokens.generated.css')

/**
 * Read out of the TypeScript source rather than imported.
 *
 * The alternative is compiling a package to run a build step that the package
 * itself is built by — and this file is three object literals, so parsing them
 * is honest rather than clever.
 */
export function tokens() {
  const source = readFileSync(path.join(root, 'packages/ui/src/tokens.ts'), 'utf8')
  const group = (name) => {
    const block = new RegExp(`export const ${name}: TokenGroup = \\{([\\s\\S]*?)\\n\\}`).exec(source)?.[1]
    if (block === undefined) throw new Error(`tokens: no group named ${name}`)
    return [...block.matchAll(/^\s*'?([a-z0-9-]+)'?:\s*(?:'([^']*)'|"([^"]*)")/gm)].map((m) => [
      m[1],
      m[2] ?? m[3],
    ])
  }
  return {
    light: group('COLOUR_LIGHT'),
    dark: group('COLOUR_DARK'),
    space: group('SPACE'),
    type: group('TYPE'),
    shape: group('SHAPE'),
    size: group('SIZE'),
  }
}

const declare = (prefix, pairs, indent = '  ') =>
  pairs.map(([name, value]) => `${indent}--ok-${prefix}-${name}: ${value};`).join('\n')

export function toCss() {
  const t = tokens()
  return `/* Generated by tools/tokens.mjs from packages/ui/src/tokens.ts. Do not edit by hand. */

:root {
${declare('colour', t.light)}
${declare('space', t.space)}
${declare('type', t.type)}
${declare('shape', t.shape)}
${declare('size', t.size)}
}

@media (prefers-color-scheme: dark) {
  :root {
${declare('colour', t.dark, '    ')}
  }
}
`
}

if (import.meta.filename === process.argv[1]) {
  const css = toCss()
  writeFileSync(OUT, css)
  console.log(`wrote ${path.relative(root, OUT)} (${css.split('\n').length} lines)`)
}
