/**
 * Wireframes derived from the renderers, not written beside them.
 *
 * Every screen record in `screens.md` points at a wireframe. Hand-written, that
 * file becomes a fourth copy of the truth — after the code, the scenario and
 * the screen record — and the one nobody updates. So it is generated: the
 * element inventory comes out of the renderer that produces it, and a test
 * asserts the committed file still matches. A screen that gains a control fails
 * the build until its wireframe is regenerated, which makes drift impossible
 * rather than merely discouraged.
 *
 * What a generated wireframe is good for is the same thing a hand-drawn one is:
 * seeing at a glance what is on a screen and in what order. What it cannot do
 * is describe intent — that lives in the screen record's Purpose line, which is
 * written by a person and quoted here.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

const root = process.cwd()

export const SCREENS = {
  'SCR-01': { title: 'First run', source: 'packages/ui/src/first-run/screen.ts' },
  'SCR-02': { title: 'Popup', source: 'packages/ui/src/popup/popup.ts' },
  'SCR-03': { title: 'In-page warning banner', source: 'packages/ui/src/banner/banner.ts' },
  'SCR-04': { title: 'Finding inspector', source: 'packages/ui/src/inspector/inspector.ts' },
  'SCR-05': { title: 'Block interstitial', source: 'packages/ui/src/interstitial/interstitial.ts' },
  'SCR-06': { title: 'Agent action gate', source: 'packages/ui/src/gate/gate.ts' },
  'SCR-07': { title: 'Findings queue', source: 'packages/ui/src/queue/queue.ts' },
  'SCR-08': { title: 'Leaks and repair', source: 'packages/ui/src/leaks/leaks.ts' },
  'SCR-09': { title: 'Extensions watch', source: 'packages/ui/src/extensions/extensions.ts' },
  'SCR-10': { title: 'Self-audit', source: 'packages/ui/src/self-audit/panel.ts' },
  'SCR-11': { title: 'Journal and weekly diff', source: 'packages/ui/src/journal/journal.ts' },
  'SCR-12': { title: 'Settings — data controls', source: 'packages/ui/src/settings/data-controls.ts' },
  'SCR-13': { title: 'Recovery checklist', source: 'packages/ui/src/recovery/recovery.ts' },
  'SCR-14': { title: 'Public domain status', source: 'apps/status-page/src/render.ts' },
}

/** Every `data-role` the renderer can emit, in the order the source names them. */
export function rolesOf(source) {
  const text = readFileSync(path.join(root, source), 'utf8')
  const roles = []
  const patterns = [
    /setAttribute\(\s*'data-role',\s*'([a-z0-9-]+)'/g,
    /\b(?:text|button|row|action)\(\s*doc,\s*'([a-z0-9-]+)'/g,
    /\b(?:text|button|row|action)\(\s*\n\s*doc,\s*\n\s*'([a-z0-9-]+)'/g,
  ]
  for (const pattern of patterns) {
    for (const match of text.matchAll(pattern)) {
      if (!roles.includes(match[1])) roles.push(match[1])
    }
  }
  return roles
}

/** The states the screen record declares, so the two documents cannot disagree. */
export function statesOf(id) {
  const screens = readFileSync(path.join(root, 'docs/ux/screens.md'), 'utf8')
  const block = screens.split(new RegExp(`^### ${id}:`, 'm'))[1]?.split(/^### SCR-/m)[0] ?? ''
  return [...block.matchAll(/^\s*\|\s*(loading|empty|error|success)\s*\|\s*([^|]+)\|/gim)].map(
    (match) => ({ state: match[1].trim(), trigger: match[2].trim() }),
  )
}

export function purposeOf(id) {
  const screens = readFileSync(path.join(root, 'docs/ux/screens.md'), 'utf8')
  const block = screens.split(new RegExp(`^### ${id}:`, 'm'))[1]?.split(/^### SCR-/m)[0] ?? ''
  return /- \*\*Purpose:\*\*\s*(.+)/.exec(block)?.[1]?.trim() ?? ''
}

export function wireframe(id) {
  const { title, source } = SCREENS[id]
  const roles = rolesOf(source)
  const states = statesOf(id)
  const purpose = purposeOf(id)

  return `<!-- Generated by tools/wireframes.mjs from ${source}. Do not edit by hand:
     run \`pnpm wireframes\` after changing the screen, and commit the result. -->

# ${id} — ${title}

**Purpose:** ${purpose}

**Elements, in the order the renderer emits them.** Each is addressable as
\`[data-role=<name>]\`, which is also how the tests reach them.

${roles.map((role) => `- \`${role}\``).join('\n')}

**States**

${
  states.length === 0
    ? '_None declared in the screen record._'
    : states.map((entry) => `- **${entry.state}** — ${entry.trigger}`).join('\n')
}

**Source of truth:** \`${source}\`. This file is derived from it; if the two
disagree, the renderer is right and this file is stale.
`
}

export function writeAll() {
  const dir = path.join(root, 'docs/ux/wireframes')
  mkdirSync(dir, { recursive: true })
  for (const id of Object.keys(SCREENS)) {
    writeFileSync(path.join(dir, `${id}.md`), wireframe(id), 'utf8')
  }
  return Object.keys(SCREENS).length
}

if (import.meta.url === `file://${process.argv[1]}`) {
  console.log(`wrote ${writeAll()} wireframes`)
}
