/* Generated by tools/public-style.mjs from packages/ui/src/tokens.ts. Do not edit by hand. */

/** Inlined by the worker: three public pages, one visual layer, tokens from one place. */
export const PUBLIC_STYLE = `/* Generated by tools/tokens.mjs from packages/ui/src/tokens.ts. Do not edit by hand. */

:root {
  --ok-colour-surface: #ffffff;
  --ok-colour-surface-sunken: #f1f5f9;
  --ok-colour-surface-raised: #ffffff;
  --ok-colour-border: #cbd5e1;
  --ok-colour-border-strong: #94a3b8;
  --ok-colour-text: #0f172a;
  --ok-colour-text-muted: #475569;
  --ok-colour-accent: #1e293b;
  --ok-colour-accent-text: #f8fafc;
  --ok-colour-focus: #2563eb;
  --ok-colour-severity-info: #0369a1;
  --ok-colour-severity-warn: #a16207;
  --ok-colour-severity-block: #b91c1c;
  --ok-space-0: 0;
  --ok-space-1: 4px;
  --ok-space-2: 8px;
  --ok-space-3: 12px;
  --ok-space-4: 16px;
  --ok-space-5: 24px;
  --ok-space-6: 32px;
  --ok-type-font-family: system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  --ok-type-font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  --ok-type-size-sm: 13px;
  --ok-type-size-base: 15px;
  --ok-type-size-lg: 19px;
  --ok-type-size-xl: 24px;
  --ok-type-line-tight: 1.25;
  --ok-type-line-base: 1.55;
  --ok-type-weight-normal: 400;
  --ok-type-weight-strong: 600;
  --ok-shape-radius: 6px;
  --ok-shape-radius-lg: 10px;
  --ok-shape-target-min: 24px;
  --ok-shape-focus-width: 2px;
  --ok-shape-focus-offset: 2px;
  --ok-shape-hairline: 1px;
  --ok-shape-severity-bar: 3px;
  --ok-size-popup: 380px;
  --ok-size-page-max: 780px;
}

@media (prefers-color-scheme: dark) {
  :root {
    --ok-colour-surface: #0f172a;
    --ok-colour-surface-sunken: #020617;
    --ok-colour-surface-raised: #1e293b;
    --ok-colour-border: #334155;
    --ok-colour-border-strong: #64748b;
    --ok-colour-text: #e2e8f0;
    --ok-colour-text-muted: #94a3b8;
    --ok-colour-accent: #e2e8f0;
    --ok-colour-accent-text: #0f172a;
    --ok-colour-focus: #60a5fa;
    --ok-colour-severity-info: #7dd3fc;
    --ok-colour-severity-warn: #fcd34d;
    --ok-colour-severity-block: #fca5a5;
  }
}

  html { color-scheme: light dark; }
  body {
    margin: 0;
    padding: var(--ok-space-5);
    background: var(--ok-colour-surface-sunken);
    color: var(--ok-colour-text);
    font-family: var(--ok-type-font-family);
    font-size: var(--ok-type-size-base);
    line-height: var(--ok-type-line-base);
  }
  main {
    max-inline-size: var(--ok-size-page-max);
    margin-inline: auto;
    padding: var(--ok-space-5);
    background: var(--ok-colour-surface);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border);
    border-radius: var(--ok-shape-radius-lg);
  }
  h1 {
    margin: 0 0 var(--ok-space-3);
    font-size: var(--ok-type-size-xl);
    line-height: var(--ok-type-line-tight);
    font-weight: var(--ok-type-weight-strong);
  }
  h2 {
    margin: var(--ok-space-5) 0 var(--ok-space-2);
    font-size: var(--ok-type-size-lg);
    line-height: var(--ok-type-line-tight);
    font-weight: var(--ok-type-weight-strong);
  }
  p { margin: 0 0 var(--ok-space-3); }
  ul, ol { margin: 0 0 var(--ok-space-3); padding-inline-start: var(--ok-space-5); }
  li { margin-block: var(--ok-space-1); }
  a { color: var(--ok-colour-focus); }
  code, pre {
    font-family: var(--ok-type-font-mono);
    font-size: var(--ok-type-size-sm);
  }
  pre {
    padding: var(--ok-space-3);
    background: var(--ok-colour-surface-sunken);
    border-radius: var(--ok-shape-radius);
    overflow-x: auto;
  }
  table { border-collapse: collapse; inline-size: 100%; }
  th, td {
    padding: var(--ok-space-2);
    border-block-end: var(--ok-shape-hairline) solid var(--ok-colour-border);
    text-align: start;
    vertical-align: top;
  }
  form { display: flex; flex-wrap: wrap; gap: var(--ok-space-2); align-items: center; }
  label { color: var(--ok-colour-text-muted); }
  input {
    min-block-size: var(--ok-shape-target-min);
    padding: var(--ok-space-1) var(--ok-space-2);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border-strong);
    border-radius: var(--ok-shape-radius);
    background: var(--ok-colour-surface);
    color: var(--ok-colour-text);
    font: inherit;
  }
  button {
    min-block-size: var(--ok-shape-target-min);
    padding: var(--ok-space-1) var(--ok-space-3);
    border: var(--ok-shape-hairline) solid var(--ok-colour-border-strong);
    border-radius: var(--ok-shape-radius);
    background: var(--ok-colour-text);
    color: var(--ok-colour-surface);
    font: inherit;
    cursor: pointer;
  }
  :focus-visible { outline: 2px solid var(--ok-colour-focus); outline-offset: 2px; }
`
